import { Ord } from './index';
declare type OrdFn<T> = (x: T, index?: number) => Ord;
export declare const sortBy: <T>(ary: T[], fn: OrdFn<T>) => T[];
export declare const sortByLazy: <T>(ary: T[], ...fns: OrdFn<T>[]) => T[];
export declare const lt: (a: Ord, b: Ord) => boolean;
export declare const eq: (a: Ord, b: Ord) => boolean;
export declare const gt: (a: Ord, b: Ord) => boolean;
export declare const lte: (a: Ord, b: Ord) => boolean;
export declare const neq: (a: Ord, b: Ord) => boolean;
export declare const gte: (a: Ord, b: Ord) => boolean;
export {};
